// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxvdamaycgeioudmjrli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dmRhbWF5Y2dlaW91ZG1qcmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDIyOTYsImV4cCI6MjA2MTIxODI5Nn0.cF2k4wLKOPL23uscVa5rQJPigEzc22ecDkh5xymHMJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);